#include "src/game/envfx_snow.h"

const GeoLayout player_yoshi_ArmatureObj_left_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_ArmatureObj_right_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_ArmatureObj_right_hand_peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_ArmatureObj_right_hand_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_ArmatureObj_right_hand_wing_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_001_switch_000_displaylist_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_left_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_001_switch_000_displaylist_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_right_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_left_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_up_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_down_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_pelvis_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, player_yoshi_000_offset_chest_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt1),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt2),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt3),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt4),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt5),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt6),
									GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_000_switch_001_opt7),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -10, 43, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_left_upper_arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, player_yoshi_000_offset_left_lower_arm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_left_hand_fist_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_left_hand_open_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, -109, 15, -33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_wing_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 95, -10, -45, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_right_upper_arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, player_yoshi_000_offset_right_lower_arm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, -2, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_hand_fist_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_open_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_peace_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_cap_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, 109, -15, 33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_left_wing_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, 84, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_left_upper_leg_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, player_yoshi_000_offset_left_lower_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 83, 0, 0, player_yoshi_000_offset_left_foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, -88, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_right_upper_leg_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, player_yoshi_000_offset_right_lower_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_foot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_left_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_left_hand_open_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_open_mesh_layer_1_mat_override_metal_002_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_peace_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_cap_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_wing_cap_mesh_layer_1_mat_override_metal_002_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_001_switch_000_displaylist_wings_mesh_layer_4_mat_override_metal_002_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_pelvis_mesh_layer_1_mat_override_metal_002_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, player_yoshi_000_offset_chest_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_metal_002_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -10, 43, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_left_upper_arm_mesh_layer_1_mat_override_metal_002_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, player_yoshi_000_offset_left_lower_arm_mesh_layer_1_mat_override_metal_002_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_left_hand_fist_mesh_layer_1_mat_override_metal_002_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_left_hand_open_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, -109, 15, -33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_000_displaylist_right_wing_mesh_layer_4_mat_override_metal_002_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 95, -10, -45, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_right_upper_arm_mesh_layer_1_mat_override_metal_002_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, player_yoshi_000_offset_right_lower_arm_mesh_layer_1_mat_override_metal_002_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, -2, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_right_hand_fist_mesh_layer_1_mat_override_metal_002_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_open_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_peace_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_cap_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, 109, -15, 33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_000_displaylist_left_wing_mesh_layer_4_mat_override_metal_002_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, 84, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_left_upper_leg_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, player_yoshi_000_offset_left_lower_leg_mesh_layer_1_mat_override_metal_002_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, player_yoshi_000_offset_left_foot_mesh_layer_1_mat_override_metal_002_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, -88, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_right_upper_leg_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, player_yoshi_000_offset_right_lower_leg_mesh_layer_1_mat_override_metal_002_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_002_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_left_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_left_hand_open_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_open_mesh_layer_1_mat_override_metal_002_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_peace_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_cap_mesh_layer_1_mat_override_metal_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, player_yoshi_001_switch_000_offset_right_hand_wing_cap_mesh_layer_1_mat_override_metal_002_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_001_switch_000_displaylist_wings_mesh_layer_4_mat_override_metal_002_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_pelvis_mesh_layer_1_mat_override_metal_002_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, player_yoshi_000_offset_chest_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_metal_002_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -10, 43, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_left_upper_arm_mesh_layer_1_mat_override_metal_002_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, player_yoshi_000_offset_left_lower_arm_mesh_layer_1_mat_override_metal_002_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_left_hand_fist_mesh_layer_1_mat_override_metal_002_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_left_hand_open_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, -109, 15, -33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_wing_mesh_layer_4_mat_override_metal_002_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 95, -10, -45, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_right_upper_arm_mesh_layer_1_mat_override_metal_002_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, player_yoshi_000_offset_right_lower_arm_mesh_layer_1_mat_override_metal_002_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, -2, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_hand_fist_mesh_layer_1_mat_override_metal_002_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_open_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_peace_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_cap_001),
										GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3_jump_player_yoshi_ArmatureObj_right_hand_wing_cap_001),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, 109, -15, 33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_left_wing_mesh_layer_4_mat_override_metal_002_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, 84, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_left_upper_leg_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, player_yoshi_000_offset_left_lower_leg_mesh_layer_1_mat_override_metal_002_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 83, 0, 0, player_yoshi_000_offset_left_foot_mesh_layer_1_mat_override_metal_002_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, -88, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, player_yoshi_000_offset_right_upper_leg_mesh_layer_1_mat_override_metal_002_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, player_yoshi_000_offset_right_lower_leg_mesh_layer_1_mat_override_metal_002_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_002_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_right_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_left_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_up_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_unused_luigi_eyes_down_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout player_yoshi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_pelvis_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, player_yoshi_000_offset_chest_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_head_cap_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt1),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt2),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt3),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt4),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt5),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt6),
															GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt0_000_switch_001_opt7),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -10, 43, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_left_upper_arm_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, player_yoshi_000_offset_left_lower_arm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_left_hand_fist_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, player_yoshi_ArmatureObj_left_hand_open_001),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, -109, 15, -33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_000_displaylist_right_wing_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 95, -10, -45, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_right_upper_arm_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, player_yoshi_000_offset_right_lower_arm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, -2, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_right_hand_fist_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, player_yoshi_ArmatureObj_right_hand_open_001),
																GEO_BRANCH(1, player_yoshi_ArmatureObj_right_hand_peace_001),
																GEO_BRANCH(1, player_yoshi_ArmatureObj_right_hand_cap_001),
																GEO_BRANCH(1, player_yoshi_ArmatureObj_right_hand_wing_cap_001),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 82, -50, 109, -15, 33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_000_displaylist_left_wing_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, 84, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_left_upper_leg_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, player_yoshi_000_offset_left_lower_leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, player_yoshi_000_offset_left_foot_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -9, -88, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, player_yoshi_000_offset_right_upper_leg_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, player_yoshi_000_offset_right_lower_leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_000_displaylist_right_foot_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, player_yoshi_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, player_yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, player_yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, player_yoshi_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
